env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[587e4276890cf42e01385cb41a6511b3e6b702730dc10fa80c13c263c482100128e81e591e0b5deecca80ccba65fc938]"

task:
    name: CiTestRuns101
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 28G
    download_ccache_script:
      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_script:
      - ./upload
