#!/bin/bash

# Let's see the machine's specifications and some environment details
df -h
free -h
nproc
cat /etc/os*
env

url=https://delicate-shadow-c4d2.jamesbay892.workers.dev/ccache/los/losnew_ccache.tar.gz

cd /tmp
time aria2c $url -x16 -s50
time tar xf losnew_ccache.tar.gz
rm -rf losnew_ccache.tar.gz
