#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://delicate-shadow-c4d2.jamesbay892.workers.dev/ccache/ci2/los_ccache.tar.gz
cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50
time tar xf los_ccache.tar.gz
find los_ccache.tar.gz -delete
