#!/bin/bash

cd /tmp

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf los_$1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
time rclone copy los_ccache.tar.gz jamesbay892:ccache/ci2 -P
