#!/bin/bash

MANIFEST=git://github.com/LineageOS/android.git
BRANCH=lineage-18.1

mkdir -p /tmp/rom
cd /tmp/rom

# Initialize the ROM source
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault

# Input git details
git config --global user.name kevinblunt1609
git config --global user.email kevinblunt1609@gmail.com

# Sync the ROM source
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Clone trees
git clone https://gitlab.com/asus-sdm660-4.19/device_asus_x00t-4.19.git --single-branch -b losZen device/asus/X00T/ --depth=1
git clone https://gitlab.com/asus-sdm660-4.19/proprietary_vendor_asus-4.19.git --single-branch -b lineage-18.1-4.19 vendor/asus/ --depth=1
git clone https://gitlab.com/asus-sdm660-4.19/kernel_asus_sdm660-4.19 --single-branch -b Stardust-4.19 kernel/asus/sdm660/ --depth=1

# Delete then clone hals
rm -r hardware/qcom-caf/msm8998/audio
rm -r hardware/qcom-caf/msm8998/media
rm -r hardware/qcom-caf/msm8998/display

git clone https://gitlab.com/asus-sdm660-4.19/android_hardware_qcom_audio --single-branch hardware/qcom-caf/msm8998/audio --depth=1
git clone https://gitlab.com/asus-sdm660-4.19/android_hardware_qcom_media --single-branch hardware/qcom-caf/msm8998/media --depth=1
git clone https://gitlab.com/asus-sdm660-4.19/android_hardware_qcom_display  --single-branch hardware/qcom-caf/msm8998/display --depth=1

# Clone repos with extra patches
rm -r vendor/codeaurora/telephony
git clone https://github.com/pranavkapoor001/android_vendor_codeaurora_telephony --single-branch vendor/codeaurora/telephony --depth=1
